id: PB0874122
initial_creation_type: input
source_metadata:
  title: Ten Royal Sūtras
  language: bo
  description: 'A collection related to the ten royal sūtras or ten sūtras of the
    king (rgyal po''i mdo bcu), which are said to have been translated upon the advice
    of Padmasambhava for Emperor Tri Songdetsen''s daily recitation:'
  volume:
    b23000397304444aaf0460fe2c6350fa:
      title: Outline of the Ten Royal Sūtras
      parent: Outlines
    c0d23104e6784c148fc618a89ea620bc:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Sūtras
    9b17513f994542379e0eedf2fdcdbf11:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Sūtras
    af1219af71f6461e97b55de88de640c7:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Sūtras
    d9541918dfd049ffb294c962336fe00c:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Sūtras
    e8369041e0784a70ac3fd7e164e90436:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Sūtras
    3061936c840645d38eddc34ab34b51d4:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Sūtras
    1ddaf7097de04916b2afc8b1502cfe11:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Sūtras
    b6ea3df742d04808ae80365035440c43:
      title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
      parent: Sūtras
    64c74225e2444caa97afc1e62da8540e:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtras
    156cf992de964fe4ad04e4aaa677f4cd:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Sūtras
created_at: '2022-03-01T06:06:38.016293'
last_modified_at: '2022-03-01T06:06:38.016295'
statistics:
  total_words: 21350
  total_non_words: 4137
quality:
  non_words_ratio: 0.19
